### PR TITLE
socket.io specs changed in 1.0; not backward compatible!!

### PR DESCRIPTION
**Pull request by mihai-chiorean**

### CODE REVIEW

**Comment by wusher** [comment]
:+1:

**Comment by shaunrader** [comment]
+1 for this!

**Comment by RickEyre** [comment]
It probably should be 0.9.6 instead of compatible with 0.9.6 because then it will install 0.9.7 and I've run into max buffer problems with that version and node-phantom.

**Comment by mihai-chiorean** [comment]
Thanks for the feedback! will update!

**Comment by mihai-chiorean** [comment]
is anyone still maintaining this?

**Pull request closed without merging**
