### PR TITLE
Adding ability to specify phantomjs startup options

### PR DESCRIPTION
**Pull request by AndrewRayCode**

### CODE REVIEW

**Comment by ewaters** [comment]
This is a great feature idea that I need as well for --disk-cache=no

**Comment by nisaacson** [comment]
This is great. Alex, any thoughts on merging?

**Comment by rehno-lindeque** [comment]
Also did the same thing here, 
https://github.com/circuithub/node-phantom/commit/10c2724698a1638087ef508bde7884135b8916fe

Didn't see the existing pull request I'm afraid.

**Comment by alexscheelmeyer** [comment]
This seems like a nice addition.

**Pull request merged**
