### PR TITLE
Allow setting of phantom viewport size

### PR DESCRIPTION
**Pull request by davidmfoley**
Adds a setViewport function to page that takes an object with width and height (in pixels):

`page.setViewport({width: 1280, height: 1024});`

This is useful if you are capturing screenshots of test failures.

### CODE REVIEW

**Comment by potmo** [comment]
+1

**Comment by davidmfoley** [comment]
@JonathanMH I fixed that issue (wasn't using the callback in our project)

**Comment by davidmfoley** [comment]
@alexscheelmeyer A couple of notes

I also changed the devDependencies to include mocha in this PR. 
I added pngjs as a devDependency so that I could render a browser screenshot, parse it as a PNG, and check that the dimensions match. There is probably a less hacky way to do this, but this was the most expedient way I could think of.

**Comment by JonathanMH** [comment]
Wow, nice! I will look through your changes and see if I can add the ClipRect method myself!

**Comment by skotchio** [comment]
What's happened with alexscheelmeyer? There is a lot of pull requests. Maybe somebody could fork and support this repo?

**Comment by potmo** [comment]
@alexscheelmeyer are you here? I can fork and maintain this project otherwise

**Comment by b0c1** [comment]
+1 and I need clipRect

**Comment by asmega** [comment]
+1

**Comment by Osmosis311** [comment]
+1 for clipRect!  Really need this one...

**Comment by alexscheelmeyer** [comment]
I have merged this into master now, will be part of next version.

**Comment by b0c1** [comment]
thnx a lot

**Comment by fjhub** [comment]
I apologize if this is in the wrong spot…

Could you specify the next version number?  I ask because I've been trying to track down an issue with a separate package which uses this package in which the rendered image size is not the expected size.  Hopefully the clipRect method will solve my issue.

…your work is appreciated.

**Comment by frolic** [comment]
For those looking for `clipRect` support, you can simply call `page.set` with your rectangle:

``` js
page.set('clipRect', {top: 0, left: 0, width: 800, height: 600}, function (err) {
  // then render...
});
```

**Pull request closed without merging**
